### ISSUE TITLE
Expected format of SLIpAddress.V6Address

### ISSUE THREAD

**Issue by remingtonc** [Cisco-Service-Layer/service-layer-objmodel#1]
https://github.com/Cisco-Service-Layer/service-layer-objmodel/blob/master/grpc/protos/sl_common_types.proto#L687-L694

I see `V6Address` specified as `bytes` but what representation of the IP address should be encoded? `packed`? Integer? What endianness? The string representation? Reconciling with Python's `IPAddressV6` [type](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv6Address).

**Comment by remingtonc** [comment]
Some investigation:

#### Integer representation to 128 bytes
`path.NexthopAddress.V6Address = int(nexthop_address).to_bytes(128, sys.byteorder)`
**Fails**: `SL_PATH_NH_INVALID_ADDR_SZ | Size of next hop IPv6 address is invalid. 0x5007.`

#### Packed Representation
`path.NexthopAddress.V6Address = nexthop_address.packed`
**Success?**: `SL_ROUTE_PATH_AFI_MISMATCH | Route and Path AFI does not match. 0x400f.`

It looks like the packed representation is correct for SL-API format, my routing usage might just be incorrect. Filing a separate issue. Will close if can confirm `packed` is the desired `bytes`-form encoding.

**Comment by arshanh** [comment]
Yes, that's correct ipv6 addresses are packed, and as mentioned in #2 v6 next hops are not supported with v4 dest addrs.

https://github.com/Cisco-Service-Layer/service-layer-objmodel/blob/master/grpc/python/src/sl_api/serializers.py#L148
